version: '3.8'

services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - API_PORT=8000
      - MAIN_MODEL=llama3
      - FALLBACK_MODEL=mistral
      - VISION_MODEL=llava
    volumes:
      - ./uploads:/app/uploads
      - ./img_content:/app/img_content
      - ./firebase_credentials.json:/app/firebase_credentials.json
      - ./gcp_service_account.json:/app/gcp_service_account.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - API_URL=http://flask-api:8000
      - OPTIMISE=True
    volumes:
      - ./img_content:/app/img_content
    depends_on:
      - flask-api
    restart: unless-stopped

networks:
  default:
    driver: bridge
